schema: gitpm/task@1
id: T-26-S73Y6P
project: P-26-7VWANM
title: Вывести старое хранилище из эксплуатации
type: task
status: backlog
lifecycle: active
acceptance_criteria_markdown:
  - Результат проверен ответственным сотрудником.
  - Связанные материалы сохранены в проекте.
parent: T-26-SQ5YK5
milestone: M-26-9HGQWY
assignees:
  - U-26-FSB3GM
  - U-26-1MV0QD
  - U-26-0225HT
  - U-26-AD9KDK
estimate_hours: 52
start: 2027-01-11
due: 2027-01-29
depends_on:
  - T-26-TSD15E
labels:
  - вывод
  - эксплуатация
