import type { MessageKey } from "../i18n.js";

type Translate = (key: MessageKey, values?: Readonly<Record<string, string | number>>) => string;

const FIELD_HINT_KEYS = [
  ["locale.label", "fieldHint.locale"],
  ["drafts.current", "fieldHint.currentDraft"],
  ["drafts.id", "fieldHint.draftId"],
  ["core.name", "fieldHint.name"],
  ["core.title", "fieldHint.title"],
  ["core.description", "fieldHint.description"],
  ["core.status", "fieldHint.status"],
  ["core.type", "fieldHint.type"],
  ["core.owner", "fieldHint.owner"],
  ["core.project", "fieldHint.project"],
  ["core.targetProject", "fieldHint.targetProject"],
  ["core.group", "fieldHint.projectGroup"],
  ["core.newGroupName", "fieldHint.newProjectGroup"],
  ["core.milestone", "fieldHint.milestone"],
  ["taskHierarchy.parent", "fieldHint.parent"],
  ["core.assignees", "fieldHint.assignees"],
  ["core.assigneeSearch", "fieldHint.assigneeSearch"],
  ["core.lifecycleFilter", "fieldHint.lifecycle"],
  ["projectPlan.start", "fieldHint.scheduleStart"],
  ["core.due", "fieldHint.scheduleFinish"],
  ["projectPlan.estimate", "fieldHint.estimate"],
  ["scheduleTracks.dependencies", "fieldHint.dependencies"],
  ["planning.heading", "fieldHint.projectTracks"],
  ["planning.primaryTrack", "fieldHint.primaryTrack"],
  ["planning.workloadTrack", "fieldHint.workloadTrack"],
  ["planning.comparisonTrack", "fieldHint.comparisonTrack"],
  ["timeEffort.person", "fieldHint.timePerson"],
  ["timeEffort.date", "fieldHint.timeDate"],
  ["timeEffort.hours", "fieldHint.timeHours"],
  ["timeEffort.category", "fieldHint.timeCategory"],
  ["timeEffort.note", "fieldHint.timeNote"],
  ["comments.add", "fieldHint.comment"],
  ["availability.kind", "fieldHint.availabilityKind"],
  ["availability.start", "fieldHint.availabilityStart"],
  ["availability.finish", "fieldHint.availabilityFinish"],
  ["availability.percent", "fieldHint.availabilityPercent"],
  ["availability.note", "fieldHint.availabilityNote"],
  ["availability.state", "fieldHint.availabilityState"],
  ["admin.email", "fieldHint.personEmail"],
  ["admin.capacity", "fieldHint.personCapacity"],
  ["admin.calendar", "fieldHint.personCalendar"],
  ["admin.members", "fieldHint.teamMembers"],
  ["admin.calendarPreset", "fieldHint.calendarPreset"],
  ["admin.weekdays", "fieldHint.calendarWeekdays"],
  ["admin.holidays", "fieldHint.calendarHolidays"],
  ["admin.defaultCalendar", "fieldHint.defaultCalendar"],
  ["admin.color", "fieldHint.configColor"],
  ["admin.statusCategory", "fieldHint.statusCategory"],
  ["admin.newTechnicalId", "fieldHint.configSlug"],
  ["admin.trackKind", "fieldHint.trackKind"],
  ["admin.capabilities", "fieldHint.trackCapabilities"],
  ["admin.newTrackTechnicalId", "fieldHint.trackSlug"],
  ["board.project", "fieldHint.boardProject"],
  ["board.statusFilter", "fieldHint.boardStatus"],
  ["board.typeFilter", "fieldHint.boardType"],
  ["board.savedView", "fieldHint.savedView"],
  ["board.viewName", "fieldHint.savedViewName"],
  ["gantt.project", "fieldHint.ganttProject"],
  ["gantt.scale", "fieldHint.ganttScale"],
  ["gantt.primaryTrack", "fieldHint.ganttPrimaryTrack"],
  ["gantt.additionalTracks", "fieldHint.ganttAdditionalTracks"],
  ["gantt.dependencyTrack", "fieldHint.ganttDependencyTrack"],
  ["workload.projectFilter", "fieldHint.workloadProject"],
  ["workload.teamFilter", "fieldHint.workloadTeam"],
  ["workload.period", "fieldHint.workloadPeriod"],
  ["actualReport.milestone", "fieldHint.actualMilestone"],
  ["actualReport.task", "fieldHint.actualTask"],
  ["actualReport.from", "fieldHint.actualFrom"],
  ["actualReport.to", "fieldHint.actualTo"],
  ["actualReport.after", "fieldHint.actualAfter"],
  ["actualReport.scopeMode", "fieldHint.actualScope"],
  ["advancedView.combineWith", "fieldHint.filterCombinator"],
  ["advancedView.field", "fieldHint.filterField"],
  ["advancedView.operator", "fieldHint.filterOperator"],
  ["advancedView.value", "fieldHint.filterValue"],
  ["advancedView.valueTo", "fieldHint.filterValueTo"],
  ["search.label", "fieldHint.globalSearch"],
  ["changes.commitMessage", "fieldHint.commitMessage"],
  ["changes.mrTitle", "fieldHint.mergeRequestTitle"],
  ["changes.mrDescription", "fieldHint.mergeRequestDescription"],
  ["history.openCommit", "fieldHint.commitId"],
  ["history.searchCommits", "fieldHint.historySearch"],
  ["history.authorFilter", "fieldHint.historyAuthor"],
  ["history.projectFilter", "fieldHint.historyProject"],
  ["history.dateFilter", "fieldHint.historyDate"],
  ["history.searchFiles", "fieldHint.historyFiles"],
  ["history.directRevertMessage", "fieldHint.directRevertMessage"],
  ["history.revertDraft", "fieldHint.revertDraft"],
  ["export.format", "fieldHint.exportFormat"],
  ["export.pdfSections", "fieldHint.exportSections"],
  ["export.projects", "fieldHint.exportProjects"],
  ["export.people", "fieldHint.exportPeople"],
  ["export.projectDetails", "fieldHint.exportProjectDetails"],
  ["export.gantt", "fieldHint.exportGantt"],
  ["export.includeGit", "fieldHint.exportGit"],
  ["repositoryConnection.repositoryUrl", "fieldHint.repositoryUrl"],
  ["repositoryConnection.gitlabUrl", "fieldHint.gitlabUrl"],
  ["repositoryConnection.gitlabProject", "fieldHint.gitlabProject"],
  ["repositoryConnection.clientId", "fieldHint.gitlabClientId"],
  ["worktree.nameLabel", "fieldHint.fileName"],
] as const satisfies readonly (readonly [MessageKey, MessageKey])[];

export function localizedFieldHints(t: Translate): ReadonlyMap<string, string> {
  const result = new Map<string, string>();
  for (const [label, hint] of FIELD_HINT_KEYS) {
    const localizedLabel = t(label);
    if (!result.has(localizedLabel)) result.set(localizedLabel, t(hint));
  }
  return result;
}
