import { useCallback, useEffect, useState, type FormEvent } from "react";
import { ENTITY_ID_PREFIX, newUniqueEntityId } from "@gitpm/shared";
import type { GitPmApi } from "./api.js";
import { formatDateOnly, message, type Locale, type MessageKey } from "./i18n.js";
import type { DraftStatus, EntityResult, GitPmDocument, GitPmRole } from "./types.js";
import { AsyncBoundary, useAsyncLoad } from "./async-data.js";
import { EditorDrawer } from "./editor-drawer.js";
import { useExternalHighlights, useReducedMotion } from "./external-updates.js";
import { upsertEntity, useFlipList } from "./optimistic-ui.js";
import { PersonLink, PersonLinks } from "./person-link.js";
import { draftReadOnlyReason } from "./draft-read-only.js";

type AdminSurface = "people" | "calendar" | "settings";
type AdminCreateEditor = "calendar" | "person" | "team" | null;
const text = (document: GitPmDocument, key: string) => typeof document[key] === "string" ? document[key] as string : "";
const number = (document: GitPmDocument, key: string) => typeof document[key] === "number" ? document[key] as number : 0;
const strings = (document: GitPmDocument, key: string) => Array.isArray(document[key]) ? (document[key] as unknown[]).filter((item): item is string => typeof item === "string") : [];
const numbers = (document: GitPmDocument, key: string) => Array.isArray(document[key]) ? (document[key] as unknown[]).filter((item): item is number => typeof item === "number") : [];
const split = (value: FormDataEntryValue | null) => String(value ?? "").split(",").map((item) => item.trim()).filter(Boolean);

export function AdminWorkspace({ api, draft, role, locale, surface, confirmAction = () => true, onOpenPerson, onChanged }: { readonly api: GitPmApi; readonly draft: DraftStatus; readonly role: GitPmRole; readonly locale: Locale; readonly surface: AdminSurface; readonly confirmAction?: (message: string) => boolean; readonly onOpenPerson?: (personId: string) => void; readonly onChanged: () => Promise<void> }) {
  const t = (key: MessageKey, values?: Readonly<Record<string, string | number>>) => message(locale, key, values);
  const [calendars, setCalendars] = useState<readonly EntityResult[]>([]);
  const [people, setPeople] = useState<readonly EntityResult[]>([]);
  const [teams, setTeams] = useState<readonly EntityResult[]>([]);
  const [statuses, setStatuses] = useState<EntityResult | null>(null);
  const [issueTypes, setIssueTypes] = useState<EntityResult | null>(null);
  const [fingerprint, setFingerprint] = useState(draft.fingerprint);
  const [error, setError] = useState<string | null>(null);
  const [peopleQuery, setPeopleQuery] = useState("");
  const [teamQuery, setTeamQuery] = useState("");
  const [createEditor, setCreateEditor] = useState<AdminCreateEditor>(null);
  const { highlights, mark } = useExternalHighlights(500);
  const loadRequest = useAsyncLoad();
  const readOnly = role !== "Maintainer" || draftReadOnlyReason(draft) !== null;

  const load = useCallback(async () => {
    await loadRequest.run(async () => {
      const [nextCalendars, nextPeople, nextTeams, nextStatuses, nextIssueTypes] = await Promise.all([
        api.listEntities(draft.draft_id, "calendars"), api.listEntities(draft.draft_id, "people"), api.listEntities(draft.draft_id, "teams"), api.getConfiguration(draft.draft_id, "statuses"), api.getConfiguration(draft.draft_id, "issue-types"),
      ]);
      return { nextCalendars, nextPeople, nextTeams, nextStatuses, nextIssueTypes };
    }, ({ nextCalendars, nextPeople, nextTeams, nextStatuses, nextIssueTypes }) => {
      setCalendars(nextCalendars); setPeople(nextPeople); setTeams(nextTeams); setStatuses(nextStatuses); setIssueTypes(nextIssueTypes);
      setFingerprint(nextCalendars[0]?.draft_fingerprint ?? nextPeople[0]?.draft_fingerprint ?? nextTeams[0]?.draft_fingerprint ?? nextStatuses.draft_fingerprint);
    });
  }, [api, draft.draft_id, draft.external_fingerprint, loadRequest.run]);
  useEffect(() => { void load(); }, [load]);

  const mutate = async (operation: () => Promise<EntityResult>) => { setError(null); try {
    const result = await operation(); setFingerprint(result.draft_fingerprint);
    if (result.document.schema === "gitpm/calendar@1") setCalendars((current) => upsertEntity(current, result));
    if (result.document.schema === "gitpm/person@1") setPeople((current) => upsertEntity(current, result));
    if (result.document.schema === "gitpm/team@1") setTeams((current) => upsertEntity(current, result));
    if (result.document.schema === "gitpm/statuses@1") setStatuses(result);
    if (result.document.schema === "gitpm/issue-types@1") setIssueTypes(result);
    mark({ [result.document.id]: ["$local"] }); await onChanged(); await load(); return result;
  } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); return null; } };
  const remove = async (operation: () => Promise<void>) => { setError(null); try { await operation(); await load(); await onChanged(); return true; } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); return false; } };
  const activeCalendars = calendars.filter((item) => item.document.lifecycle === "active");
  const activePeople = people.filter((item) => item.document.lifecycle === "active");
  const visiblePeople = activePeople.filter((item) => `${text(item.document, "name")} ${text(item.document, "email")}`.toLocaleLowerCase(locale).includes(peopleQuery.trim().toLocaleLowerCase(locale)));
  const activeTeams = teams.filter((item) => item.document.lifecycle === "active");
  const peopleNames = new Map(activePeople.map((item) => [item.document.id, text(item.document, "name")]));
  const visibleTeams = activeTeams.filter((item) => `${text(item.document, "name")} ${strings(item.document, "members").map((id) => peopleNames.get(id) ?? "").join(" ")}`.toLocaleLowerCase(locale).includes(teamQuery.trim().toLocaleLowerCase(locale)));
  const teamsByPerson = new Map(activePeople.map((person) => [person.document.id, activeTeams.filter((team) => strings(team.document, "members").includes(person.document.id))]));
  const confirmDelete = (name: string) => confirmAction(t("core.deleteConfirm", { name }));
  const surfaceHeading: MessageKey = surface === "people" ? "nav.people" : surface === "calendar" ? "nav.calendar" : "nav.settings";

  const createCalendar = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const document = { schema: "gitpm/calendar@1", id: newUniqueEntityId(ENTITY_ID_PREFIX.calendar, new Set(calendars.map((item) => item.document.id))), name: String(data.get("name")), working_weekdays: data.getAll("weekdays").map(Number), holidays: split(data.get("holidays")), lifecycle: "active" } as GitPmDocument; void mutate(async () => await api.createEntity(draft.draft_id, "calendars", fingerprint, document)).then((result) => { if (result !== null) setCreateEditor(null); }); };
  const createPerson = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const email = String(data.get("email") ?? ""); const calendar = String(data.get("calendar") ?? ""); const document = { schema: "gitpm/person@1", id: newUniqueEntityId(ENTITY_ID_PREFIX.person, new Set(people.map((item) => item.document.id))), name: String(data.get("name")), weekly_capacity_hours: Number(data.get("capacity")), lifecycle: "active", ...(calendar ? { calendar } : {}), ...(email ? { email } : {}) } as GitPmDocument; void mutate(async () => await api.createEntity(draft.draft_id, "people", fingerprint, document)).then((result) => { if (result !== null) setCreateEditor(null); }); };
  const createTeam = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const document = { schema: "gitpm/team@1", id: newUniqueEntityId(ENTITY_ID_PREFIX.team, new Set(teams.map((item) => item.document.id))), name: String(data.get("name")), members: data.getAll("members").map(String), lifecycle: "active" } as GitPmDocument; void mutate(async () => await api.createEntity(draft.draft_id, "teams", fingerprint, document)).then((result) => { if (result !== null) setCreateEditor(null); }); };

  return <section className="admin-workspace"><div className="section-heading"><span className="eyebrow draft-context-id">{draft.draft_id}</span><h2 aria-hidden="true">{t(surfaceHeading)}</h2></div>
    {role !== "Maintainer" && <div className="alert warning">{t("admin.maintainerOnly")}</div>}{error !== null && <div className="alert error">{error}</div>}
    <AsyncBoundary state={loadRequest.state} loading={t("status.loading")} retry={() => { void load(); }} error={(loadError, retry) => <div className="alert error">{loadError}<button onClick={retry}>{t("status.retry")}</button></div>}>
    <>
    {surface === "calendar" && <section className="card"><button className="primary editor-trigger" disabled={readOnly} onClick={() => setCreateEditor("calendar")} type="button">+ {t("admin.createCalendar")}</button><EditorDrawer closeLabel={t("core.closeEditor")} onClose={() => setCreateEditor(null)} open={createEditor === "calendar"} title={t("admin.createCalendar")}><form className="editor-drawer-form" onSubmit={createCalendar}><label>{t("core.name")}<input name="name" required /></label><WeekdayChecks selected={[1, 2, 3, 4, 5]} t={t} /><label>{t("admin.holidays")}<input name="holidays" placeholder="2026-01-01" /></label><div className="editor-drawer-actions"><button onClick={() => setCreateEditor(null)} type="button">{t("core.cancel")}</button><button className="primary" disabled={readOnly}>{t("admin.createCalendar")}</button></div></form></EditorDrawer><div className="admin-grid">{activeCalendars.map((entity) => <div className={highlights[entity.document.id] ? "recently-changed" : ""} key={entity.document.id}><CalendarEditor {...{ api, draft, entity, fingerprint, readOnly, t, locale, mutate, remove, confirmDelete }} /></div>)}</div></section>}
    {surface === "people" && <div className="people-admin-sections"><section className="card directory-card"><div className="card-heading"><h3>{t("admin.people")}</h3><label className="search-field">{t("admin.peopleSearch")}<input type="search" value={peopleQuery} onChange={(event) => setPeopleQuery(event.target.value)} /></label></div><button className="primary editor-trigger" disabled={readOnly || activeCalendars.length === 0} onClick={() => setCreateEditor("person")} type="button">+ {t("admin.createPerson")}</button><EditorDrawer closeLabel={t("core.closeEditor")} onClose={() => setCreateEditor(null)} open={createEditor === "person"} title={t("admin.createPerson")}><form className="editor-drawer-form" onSubmit={createPerson}><label>{t("core.name")}<input name="name" required /></label><label>{t("admin.email")}<input name="email" type="email" /></label><label>{t("admin.capacity")}<input name="capacity" type="number" min="0" step="0.25" defaultValue="40" required /></label><label>{t("admin.calendar")}<select name="calendar"><option value="">{t("admin.defaultCalendar")}</option>{activeCalendars.map((item) => <option value={item.document.id} key={item.document.id}>{text(item.document, "name")}</option>)}</select></label><div className="editor-drawer-actions"><button onClick={() => setCreateEditor(null)} type="button">{t("core.cancel")}</button><button className="primary" disabled={readOnly || activeCalendars.length === 0}>{t("admin.createPerson")}</button></div></form></EditorDrawer><div className="directory-table-wrap"><table className="directory-table people-directory-table"><thead><tr><th>{t("admin.person")}</th><th>{t("admin.email")}</th><th>{t("admin.teams")}</th><th>{t("admin.capacity")}</th><th>{t("admin.calendar")}</th></tr></thead><tbody>{visiblePeople.map((entity) => { const calendar = activeCalendars.find((item) => item.document.id === text(entity.document, "calendar")); const personTeams = teamsByPerson.get(entity.document.id) ?? []; return <tr className={highlights[entity.document.id] ? "recently-changed" : ""} key={entity.document.id}><th><PersonLink name={text(entity.document, "name")} onOpen={onOpenPerson} personId={entity.document.id} /></th><td>{text(entity.document, "email") || "—"}</td><td>{personTeams.length === 0 ? "—" : personTeams.map((team) => text(team.document, "name")).join(", ")}</td><td>{t("people.hoursPerWeek", { count: number(entity.document, "weekly_capacity_hours") })}</td><td>{calendar === undefined ? "—" : text(calendar.document, "name")}</td></tr>; })}</tbody></table></div></section>
      <section className="card directory-card"><div className="card-heading"><h3>{t("admin.teams")}</h3><label className="search-field">{t("admin.teamSearch")}<input type="search" value={teamQuery} onChange={(event) => setTeamQuery(event.target.value)} /></label></div><button className="primary editor-trigger" disabled={readOnly} onClick={() => setCreateEditor("team")} type="button">+ {t("admin.createTeam")}</button><EditorDrawer closeLabel={t("core.closeEditor")} onClose={() => setCreateEditor(null)} open={createEditor === "team"} title={t("admin.createTeam")}><form className="editor-drawer-form" onSubmit={createTeam}><label>{t("core.name")}<input name="name" required /></label><MemberChecks people={activePeople} selected={[]} t={t} /><div className="editor-drawer-actions"><button onClick={() => setCreateEditor(null)} type="button">{t("core.cancel")}</button><button className="primary" disabled={readOnly}>{t("admin.createTeam")}</button></div></form></EditorDrawer><div className="directory-table-wrap"><table className="directory-table team-directory-table"><thead><tr><th>{t("admin.team")}</th><th>{t("admin.members")}</th><th>{t("admin.actions")}</th></tr></thead><tbody>{visibleTeams.map((entity) => <tr className={highlights[entity.document.id] ? "recently-changed" : ""} key={entity.document.id}><TeamEditor {...{ api, draft, entity, fingerprint, readOnly, t, people: activePeople, mutate, remove, confirmDelete, onOpenPerson }} /></tr>)}</tbody></table></div></section></div>}
    {surface === "settings" && <section className="card"><h3>{t("admin.settings")}</h3><div className="admin-columns">{statuses !== null && <ConfigEditor api={api} draft={draft} entity={statuses} kind="statuses" listKey="statuses" title={t("admin.statuses")} readOnly={readOnly} t={t} mutate={mutate} />}{issueTypes !== null && <ConfigEditor api={api} draft={draft} entity={issueTypes} kind="issue-types" listKey="issue_types" title={t("admin.issueTypes")} readOnly={readOnly} t={t} mutate={mutate} />}</div></section>}
    </>
    </AsyncBoundary>
  </section>;
}

interface EditorProps { readonly api: GitPmApi; readonly draft: DraftStatus; readonly entity: EntityResult; readonly fingerprint: string; readonly readOnly: boolean; readonly t: (key: MessageKey, values?: Readonly<Record<string, string | number>>) => string; readonly mutate: (operation: () => Promise<EntityResult>) => Promise<EntityResult | null>; readonly remove: (operation: () => Promise<void>) => Promise<boolean>; readonly confirmDelete: (name: string) => boolean }
const ActionButtons = ({ disabled, save, archive, remove, close, t }: { disabled: boolean; save: (form: HTMLFormElement) => Promise<boolean>; archive: () => Promise<boolean>; remove: () => Promise<boolean>; close: () => void; t: (key: MessageKey) => string }) => <div className="editor-drawer-actions"><details className="more-actions"><summary>{t("core.moreActions")}</summary><div><button type="button" disabled={disabled} onClick={() => { void archive().then((success) => { if (success) close(); }); }}>{t("core.archive")}</button><button type="button" className="danger" disabled={disabled} onClick={() => { void remove().then((success) => { if (success) close(); }); }}>{t("core.delete")}</button></div></details><button onClick={close} type="button">{t("core.cancel")}</button><button type="button" className="primary" disabled={disabled} onClick={(event) => { if (event.currentTarget.form !== null) void save(event.currentTarget.form).then((success) => { if (success) close(); }); }}>{t("core.save")}</button></div>;

function CalendarEditor(props: EditorProps & { readonly locale: Locale }) {
  const { api, draft, entity, fingerprint, readOnly, t, locale, mutate, remove, confirmDelete } = props;
  const [open, setOpen] = useState(false);
  const name = text(entity.document, "name");
  const weekdays = numbers(entity.document, "working_weekdays");
  const holidays = strings(entity.document, "holidays").filter((date) => /^\d{4}-\d{2}-\d{2}$/u.test(date)).sort().slice(0, 3);
  const submit = async (form: HTMLFormElement) => { const data = new FormData(form); return await mutate(async () => await api.updateEntity(draft.draft_id, "calendars", entity, fingerprint, { ...entity.document, name: String(data.get("name")), working_weekdays: data.getAll("weekdays").map(Number), holidays: split(data.get("holidays")) })) !== null; };
  return <article className="admin-card admin-card-summary"><strong>{name}</strong><div aria-label={t("admin.weekPreview")} className="calendar-week-preview">{[1, 2, 3, 4, 5, 6, 7].map((day) => <span className={weekdays.includes(day) ? "working" : "off"} key={day}>{t(`admin.day${day}` as MessageKey)}</span>)}</div><div className="calendar-exceptions"><span>{t("admin.nextHolidays")}</span>{holidays.length === 0 ? <small>{t("admin.noHolidays")}</small> : holidays.map((date) => <time dateTime={date} key={date}>{formatDateOnly(locale, date)}</time>)}</div><button className="editor-trigger" onClick={() => setOpen(true)} type="button">{t("admin.editCalendar")}</button><EditorDrawer closeLabel={t("core.closeEditor")} onClose={() => setOpen(false)} open={open} title={`${t("admin.editCalendar")}: ${name}`}><form className="editor-drawer-form" onSubmit={(event) => event.preventDefault()}><label>{t("core.name")}<input name="name" aria-label={`${t("core.name")} ${name}`} defaultValue={name} /></label><WeekdayChecks selected={weekdays} t={t} /><label>{t("admin.holidays")}<input name="holidays" aria-label={`${t("admin.holidays")} ${name}`} defaultValue={strings(entity.document, "holidays").join(",")} /></label><ActionButtons disabled={readOnly} t={t} close={() => setOpen(false)} save={submit} archive={async () => await mutate(async () => await api.archiveEntity(draft.draft_id, "calendars", entity, fingerprint)) !== null} remove={async () => confirmDelete(name) && await remove(async () => await api.deleteEntity(draft.draft_id, "calendars", entity, fingerprint))} /></form></EditorDrawer></article>;
}

function MemberChecks({ people, selected, t }: { people: readonly EntityResult[]; selected: readonly string[]; t: (key: MessageKey) => string }) { return <fieldset><legend>{t("admin.members")}</legend>{people.map((person) => <label key={person.document.id}><input type="checkbox" name="members" value={person.document.id} defaultChecked={selected.includes(person.document.id)} />{text(person.document, "name")}</label>)}</fieldset>; }
function WeekdayChecks({ selected, t }: { selected: readonly number[]; t: (key: MessageKey) => string }) { return <fieldset className="weekday-checks"><legend>{t("admin.weekdays")}</legend>{[1, 2, 3, 4, 5, 6, 7].map((day) => <label key={day}><input type="checkbox" name="weekdays" value={day} defaultChecked={selected.includes(day)} />{t(`admin.day${day}` as MessageKey)}</label>)}</fieldset>; }
function TeamEditor(props: EditorProps & { people: readonly EntityResult[]; readonly onOpenPerson?: (personId: string) => void }) {
  const { api, draft, entity, fingerprint, readOnly, t, people, mutate, remove, confirmDelete, onOpenPerson } = props;
  const [open, setOpen] = useState(false);
  const name = text(entity.document, "name");
  const selected = strings(entity.document, "members");
  const update = async (form: HTMLFormElement) => { const data = new FormData(form); return await mutate(async () => await api.updateEntity(draft.draft_id, "teams", entity, fingerprint, { ...entity.document, name: String(data.get("name")), members: data.getAll("members").map(String) })) !== null; };
  return <><th>{name}</th><td><PersonLinks empty={t("admin.noMembers")} onOpen={onOpenPerson} people={people} personIds={selected} /></td><td><button className="editor-trigger" onClick={() => setOpen(true)} type="button">{t("admin.editTeam")}</button><EditorDrawer closeLabel={t("core.closeEditor")} onClose={() => setOpen(false)} open={open} title={`${t("admin.editTeam")}: ${name}`}><form className="editor-drawer-form" onSubmit={(event) => event.preventDefault()}><label>{t("core.name")}<input name="name" aria-label={`${t("core.name")} ${name}`} defaultValue={name} /></label><MemberChecks people={people} selected={selected} t={t} /><ActionButtons disabled={readOnly} t={t} close={() => setOpen(false)} save={update} archive={async () => await mutate(async () => await api.archiveEntity(draft.draft_id, "teams", entity, fingerprint)) !== null} remove={async () => confirmDelete(name) && await remove(async () => await api.deleteEntity(draft.draft_id, "teams", entity, fingerprint))} /></form></EditorDrawer></td></>;
}

interface ConfigValue { readonly slug: string; readonly title: string; readonly color: string; readonly active: boolean }
function ConfigEditor({ api, draft, entity, kind, listKey, title, readOnly, t, mutate }: { readonly api: GitPmApi; readonly draft: DraftStatus; readonly entity: EntityResult; readonly kind: "statuses" | "issue-types"; readonly listKey: "statuses" | "issue_types"; readonly title: string; readonly readOnly: boolean; readonly t: (key: MessageKey, values?: Readonly<Record<string, string | number>>) => string; readonly mutate: (operation: () => Promise<EntityResult>) => Promise<EntityResult | null> }) {
  const [open, setOpen] = useState(false);
  const entityValues = Array.isArray(entity.document[listKey]) ? entity.document[listKey] as ConfigValue[] : [];
  const [values, setValues] = useState(entityValues);
  const [busy, setBusy] = useState(false);
  const [savingRows, setSavingRows] = useState<ReadonlySet<string>>(new Set());
  const { highlights: recentRows, mark: markRows } = useExternalHighlights(500);
  const formRef = useFlipList<HTMLFormElement>(useReducedMotion());
  useEffect(() => setValues(entityValues), [entity]);
  const readValues = (form: HTMLFormElement) => { const data = new FormData(form); return values.map((item, index) => ({ slug: item.slug, title: String(data.get(`title-${index}`)), color: String(data.get(`color-${index}`)), active: data.get(`active-${index}`) === "on" })); };
  const persist = async (next: readonly ConfigValue[], onPersisted?: () => void) => {
    const previous = values; setValues([...next]); setBusy(true);
    const result = await mutate(async () => { const saved = await api.updateConfiguration(draft.draft_id, kind, entity, entity.draft_fingerprint, { ...entity.document, [listKey]: next }); setBusy(false); onPersisted?.(); return saved; });
    if (result === null) setValues(previous);
    setBusy(false); return result;
  };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void persist(readValues(event.currentTarget)).then((result) => { if (result !== null) setOpen(false); }); };
  const move = (form: HTMLFormElement, index: number, offset: number) => { const next = readValues(form); const target = index + offset; if (target < 0 || target >= next.length) return; const first = next[index]!; const second = next[target]!; [next[index], next[target]] = [second, first]; const rows = { [first.slug]: ["order"], [second.slug]: ["order"] }; setSavingRows(new Set([first.slug, second.slug])); void persist(next, () => { setSavingRows(new Set()); markRows(rows); }).finally(() => setSavingRows(new Set())); };
  return <article className="config-editor config-summary"><h4>{title}</h4><div className="config-summary-values">{values.map((item) => <span className="config-preview" key={item.slug} style={{ borderColor: item.color }}>{item.title}</span>)}</div><button className="editor-trigger" onClick={() => setOpen(true)} type="button">{t("core.edit")}</button><EditorDrawer closeLabel={t("core.closeEditor")} onClose={() => setOpen(false)} open={open} title={`${t("core.edit")}: ${title}`}><form className="editor-drawer-form config-editor-form" onSubmit={submit} ref={formRef}><p className="config-hint">{t("admin.slugHint")}</p>{values.map((item, index) => <div className={`config-row${recentRows[item.slug] ? " recently-changed" : ""}${savingRows.has(item.slug) ? " is-saving" : ""}`} data-flip-key={`config:${kind}:${item.slug}`} key={item.slug}><div className="config-identity"><code>{item.slug}</code><span className="config-preview" style={{ borderColor: item.color }}>{item.title}</span></div><input name={`title-${index}`} aria-label={`${title} ${item.slug}`} defaultValue={item.title} /><label className="color-field"><input type="color" aria-label={`${t("admin.colorPicker")} ${item.slug}`} defaultValue={/^#[0-9a-f]{6}$/iu.test(item.color) ? item.color : "#777777"} onChange={(event) => { const input = event.currentTarget.nextElementSibling as HTMLInputElement | null; if (input !== null) input.value = event.currentTarget.value; }} /><input name={`color-${index}`} aria-label={`${t("admin.color")} ${item.slug}`} defaultValue={item.color} /></label><label><input type="checkbox" name={`active-${index}`} defaultChecked={item.active} />{t("admin.active")}</label><div className="config-order"><button aria-label={t("admin.moveUp", { name: item.title })} disabled={readOnly || busy || index === 0} onClick={(event) => { if (event.currentTarget.form !== null) move(event.currentTarget.form, index, -1); }} type="button">↑</button><button aria-label={t("admin.moveDown", { name: item.title })} disabled={readOnly || busy || index === values.length - 1} onClick={(event) => { if (event.currentTarget.form !== null) move(event.currentTarget.form, index, 1); }} type="button">↓</button></div></div>)}<div className="editor-drawer-actions"><button onClick={() => setOpen(false)} type="button">{t("core.cancel")}</button><button className="primary" disabled={readOnly || busy}>{t("core.save")}</button></div></form></EditorDrawer></article>;
}
