import { useCallback, useEffect, useState, type FormEvent } from "react";
import { ENTITY_ID_PREFIX, newUniqueEntityId } from "@gitpm/shared";
import type { GitPmApi } from "./api.js";
import { message, type Locale, type MessageKey } from "./i18n.js";
import type { DraftStatus, EntityResult, GitPmDocument, GitPmRole } from "./types.js";

type AdminSurface = "people" | "calendar" | "settings";
const text = (document: GitPmDocument, key: string) => typeof document[key] === "string" ? document[key] as string : "";
const number = (document: GitPmDocument, key: string) => typeof document[key] === "number" ? document[key] as number : 0;
const strings = (document: GitPmDocument, key: string) => Array.isArray(document[key]) ? (document[key] as unknown[]).filter((item): item is string => typeof item === "string") : [];
const numbers = (document: GitPmDocument, key: string) => Array.isArray(document[key]) ? (document[key] as unknown[]).filter((item): item is number => typeof item === "number") : [];
const split = (value: FormDataEntryValue | null) => String(value ?? "").split(",").map((item) => item.trim()).filter(Boolean);

export function AdminWorkspace({ api, draft, role, locale, surface, onChanged }: { readonly api: GitPmApi; readonly draft: DraftStatus; readonly role: GitPmRole; readonly locale: Locale; readonly surface: AdminSurface; readonly onChanged: () => Promise<void> }) {
  const t = (key: MessageKey) => message(locale, key);
  const [calendars, setCalendars] = useState<readonly EntityResult[]>([]);
  const [people, setPeople] = useState<readonly EntityResult[]>([]);
  const [teams, setTeams] = useState<readonly EntityResult[]>([]);
  const [statuses, setStatuses] = useState<EntityResult | null>(null);
  const [issueTypes, setIssueTypes] = useState<EntityResult | null>(null);
  const [fingerprint, setFingerprint] = useState(draft.fingerprint);
  const [error, setError] = useState<string | null>(null);
  const readOnly = role !== "Maintainer" || draft.writer_mode !== "ui" || draft.state !== "open" || draft.changed_externally === true;

  const load = useCallback(async () => {
    const [nextCalendars, nextPeople, nextTeams, nextStatuses, nextIssueTypes] = await Promise.all([
      api.listEntities(draft.draft_id, "calendars"), api.listEntities(draft.draft_id, "people"), api.listEntities(draft.draft_id, "teams"), api.getConfiguration(draft.draft_id, "statuses"), api.getConfiguration(draft.draft_id, "issue-types"),
    ]);
    setCalendars(nextCalendars); setPeople(nextPeople); setTeams(nextTeams); setStatuses(nextStatuses); setIssueTypes(nextIssueTypes);
    setFingerprint(nextCalendars[0]?.draft_fingerprint ?? nextPeople[0]?.draft_fingerprint ?? nextTeams[0]?.draft_fingerprint ?? nextStatuses.draft_fingerprint);
  }, [api, draft.draft_id, draft.external_fingerprint]);
  useEffect(() => { void load().catch((caught) => setError(caught instanceof Error ? caught.message : String(caught))); }, [load]);

  const mutate = async (operation: () => Promise<EntityResult>) => { setError(null); try { const result = await operation(); setFingerprint(result.draft_fingerprint); await load(); await onChanged(); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } };
  const remove = async (operation: () => Promise<void>) => { setError(null); try { await operation(); await load(); await onChanged(); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } };
  const activeCalendars = calendars.filter((item) => item.document.lifecycle === "active");
  const activePeople = people.filter((item) => item.document.lifecycle === "active");
  const activeTeams = teams.filter((item) => item.document.lifecycle === "active");

  const createCalendar = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const document = { schema: "gitpm/calendar@1", id: newUniqueEntityId(ENTITY_ID_PREFIX.calendar, new Set(calendars.map((item) => item.document.id))), name: String(data.get("name")), working_weekdays: split(data.get("weekdays")).map(Number), holidays: split(data.get("holidays")), lifecycle: "active" } as GitPmDocument; void mutate(async () => await api.createEntity(draft.draft_id, "calendars", fingerprint, document)); event.currentTarget.reset(); };
  const createPerson = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const email = String(data.get("email") ?? ""); const document = { schema: "gitpm/person@1", id: newUniqueEntityId(ENTITY_ID_PREFIX.person, new Set(people.map((item) => item.document.id))), name: String(data.get("name")), weekly_capacity_hours: Number(data.get("capacity")), calendar: String(data.get("calendar")), lifecycle: "active", ...(email ? { email } : {}) } as GitPmDocument; void mutate(async () => await api.createEntity(draft.draft_id, "people", fingerprint, document)); event.currentTarget.reset(); };
  const createTeam = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const document = { schema: "gitpm/team@1", id: newUniqueEntityId(ENTITY_ID_PREFIX.team, new Set(teams.map((item) => item.document.id))), name: String(data.get("name")), members: data.getAll("members").map(String), lifecycle: "active" } as GitPmDocument; void mutate(async () => await api.createEntity(draft.draft_id, "teams", fingerprint, document)); event.currentTarget.reset(); };

  return <section className="admin-workspace"><div className="section-heading"><span className="eyebrow draft-context-id">{draft.draft_id}</span><h2>{t("admin.heading")}</h2></div>
    {role !== "Maintainer" && <div className="alert warning">{t("admin.maintainerOnly")}</div>}{error !== null && <div className="alert error">{error}</div>}
    {surface === "calendar" && <section className="card"><h3>{t("admin.calendars")}</h3><form className="admin-create" onSubmit={createCalendar}><input name="name" aria-label={t("core.name")} placeholder={t("core.name")} required /><input name="weekdays" aria-label={t("admin.weekdays")} defaultValue="1,2,3,4,5" required /><input name="holidays" aria-label={t("admin.holidays")} placeholder="2026-01-01" /><button className="primary" disabled={readOnly}>{t("admin.createCalendar")}</button></form><div className="admin-grid">{activeCalendars.map((entity) => <CalendarEditor key={entity.document.id} {...{ api, draft, entity, fingerprint, readOnly, t, mutate, remove }} />)}</div></section>}
    {surface === "people" && <div className="admin-columns"><section className="card"><h3>{t("admin.people")}</h3><form className="admin-create" onSubmit={createPerson}><input name="name" aria-label={t("core.name")} placeholder={t("core.name")} required /><input name="email" type="email" aria-label={t("admin.email")} placeholder={t("admin.email")} /><input name="capacity" type="number" min="0" step="0.25" defaultValue="40" aria-label={t("admin.capacity")} required /><select name="calendar" aria-label={t("admin.calendar")} required>{activeCalendars.map((item) => <option value={item.document.id} key={item.document.id}>{text(item.document, "name")}</option>)}</select><button className="primary" disabled={readOnly || activeCalendars.length === 0}>{t("admin.createPerson")}</button></form><div className="admin-grid">{activePeople.map((entity) => <PersonEditor key={entity.document.id} {...{ api, draft, entity, fingerprint, readOnly, t, calendars: activeCalendars, mutate, remove }} />)}</div></section>
      <section className="card"><h3>{t("admin.teams")}</h3><form className="admin-create" onSubmit={createTeam}><input name="name" aria-label={t("core.name")} placeholder={t("core.name")} required /><MemberChecks people={activePeople} selected={[]} t={t} /><button className="primary" disabled={readOnly}>{t("admin.createTeam")}</button></form><div className="admin-grid">{activeTeams.map((entity) => <TeamEditor key={entity.document.id} {...{ api, draft, entity, fingerprint, readOnly, t, people: activePeople, mutate, remove }} />)}</div></section></div>}
    {surface === "settings" && <section className="card"><h3>{t("admin.settings")}</h3><div className="alert info">{t("admin.noServerConfig")}</div><div className="admin-columns">{statuses !== null && <ConfigEditor api={api} draft={draft} entity={statuses} kind="statuses" listKey="statuses" title={t("admin.statuses")} readOnly={readOnly} t={t} mutate={mutate} />}{issueTypes !== null && <ConfigEditor api={api} draft={draft} entity={issueTypes} kind="issue-types" listKey="issue_types" title={t("admin.issueTypes")} readOnly={readOnly} t={t} mutate={mutate} />}</div></section>}
  </section>;
}

interface EditorProps { readonly api: GitPmApi; readonly draft: DraftStatus; readonly entity: EntityResult; readonly fingerprint: string; readonly readOnly: boolean; readonly t: (key: MessageKey) => string; readonly mutate: (operation: () => Promise<EntityResult>) => Promise<void>; readonly remove: (operation: () => Promise<void>) => Promise<void> }
const ActionButtons = ({ disabled, save, archive, remove, t }: { disabled: boolean; save: (form: HTMLFormElement) => void; archive: () => void; remove: () => void; t: (key: MessageKey) => string }) => <div className="admin-actions"><button type="button" className="primary" disabled={disabled} onClick={(event) => { if (event.currentTarget.form !== null) save(event.currentTarget.form); }}>{t("core.save")}</button><button type="button" disabled={disabled} onClick={archive}>{t("core.archive")}</button><button type="button" disabled={disabled} onClick={remove}>{t("core.delete")}</button></div>;

function CalendarEditor(props: EditorProps) { const { api, draft, entity, fingerprint, readOnly, t, mutate, remove } = props; const submit = (form: HTMLFormElement) => { const data = new FormData(form); void mutate(async () => await api.updateEntity(draft.draft_id, "calendars", entity, fingerprint, { ...entity.document, name: String(data.get("name")), working_weekdays: split(data.get("weekdays")).map(Number), holidays: split(data.get("holidays")) })); }; return <form className="admin-card" onSubmit={(event) => event.preventDefault()}><input name="name" aria-label={`${t("core.name")} ${text(entity.document, "name")}`} defaultValue={text(entity.document, "name")} /><input name="weekdays" aria-label={`${t("admin.weekdays")} ${text(entity.document, "name")}`} defaultValue={numbers(entity.document, "working_weekdays").join(",")} /><input name="holidays" aria-label={`${t("admin.holidays")} ${text(entity.document, "name")}`} defaultValue={strings(entity.document, "holidays").join(",")} /><ActionButtons disabled={readOnly} t={t} save={submit} archive={() => { void mutate(async () => await api.archiveEntity(draft.draft_id, "calendars", entity, fingerprint)); }} remove={() => { void remove(async () => await api.deleteEntity(draft.draft_id, "calendars", entity, fingerprint)); }} /></form>; }

function PersonEditor(props: EditorProps & { calendars: readonly EntityResult[] }) { const { api, draft, entity, fingerprint, readOnly, t, calendars, mutate, remove } = props; const update = (form: HTMLFormElement) => { const data = new FormData(form); const email = String(data.get("email")); void mutate(async () => await api.updateEntity(draft.draft_id, "people", entity, fingerprint, { ...entity.document, name: String(data.get("name")), email: email || undefined, weekly_capacity_hours: Number(data.get("capacity")), calendar: String(data.get("calendar")) })); }; return <form className="admin-card" onSubmit={(event) => event.preventDefault()}><input name="name" aria-label={`${t("core.name")} ${text(entity.document, "name")}`} defaultValue={text(entity.document, "name")} /><input name="email" aria-label={`${t("admin.email")} ${text(entity.document, "name")}`} defaultValue={text(entity.document, "email")} /><input name="capacity" type="number" min="0" step="0.25" aria-label={`${t("admin.capacity")} ${text(entity.document, "name")}`} defaultValue={number(entity.document, "weekly_capacity_hours")} /><select name="calendar" aria-label={`${t("admin.calendar")} ${text(entity.document, "name")}`} defaultValue={text(entity.document, "calendar")}>{calendars.map((item) => <option key={item.document.id} value={item.document.id}>{text(item.document, "name")}</option>)}</select><ActionButtons disabled={readOnly} t={t} save={update} archive={() => { void mutate(async () => await api.archiveEntity(draft.draft_id, "people", entity, fingerprint)); }} remove={() => { void remove(async () => await api.deleteEntity(draft.draft_id, "people", entity, fingerprint)); }} /></form>; }

function MemberChecks({ people, selected, t }: { people: readonly EntityResult[]; selected: readonly string[]; t: (key: MessageKey) => string }) { return <fieldset><legend>{t("admin.members")}</legend>{people.map((person) => <label key={person.document.id}><input type="checkbox" name="members" value={person.document.id} defaultChecked={selected.includes(person.document.id)} />{text(person.document, "name")}</label>)}</fieldset>; }
function TeamEditor(props: EditorProps & { people: readonly EntityResult[] }) { const { api, draft, entity, fingerprint, readOnly, t, people, mutate, remove } = props; const update = (form: HTMLFormElement) => { const data = new FormData(form); void mutate(async () => await api.updateEntity(draft.draft_id, "teams", entity, fingerprint, { ...entity.document, name: String(data.get("name")), members: data.getAll("members").map(String) })); }; return <form className="admin-card" onSubmit={(event) => event.preventDefault()}><input name="name" aria-label={`${t("core.name")} ${text(entity.document, "name")}`} defaultValue={text(entity.document, "name")} /><MemberChecks people={people} selected={strings(entity.document, "members")} t={t} /><ActionButtons disabled={readOnly} t={t} save={update} archive={() => { void mutate(async () => await api.archiveEntity(draft.draft_id, "teams", entity, fingerprint)); }} remove={() => { void remove(async () => await api.deleteEntity(draft.draft_id, "teams", entity, fingerprint)); }} /></form>; }

interface ConfigValue { readonly slug: string; readonly title: string; readonly color: string; readonly active: boolean }
function ConfigEditor({ api, draft, entity, kind, listKey, title, readOnly, t, mutate }: { readonly api: GitPmApi; readonly draft: DraftStatus; readonly entity: EntityResult; readonly kind: "statuses" | "issue-types"; readonly listKey: "statuses" | "issue_types"; readonly title: string; readonly readOnly: boolean; readonly t: (key: MessageKey) => string; readonly mutate: (operation: () => Promise<EntityResult>) => Promise<void> }) { const values = Array.isArray(entity.document[listKey]) ? entity.document[listKey] as ConfigValue[] : []; const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const next = values.map((item, index) => ({ slug: item.slug, title: String(data.get(`title-${index}`)), color: String(data.get(`color-${index}`)), active: data.get(`active-${index}`) === "on" })); void mutate(async () => await api.updateConfiguration(draft.draft_id, kind, entity, entity.draft_fingerprint, { ...entity.document, [listKey]: next })); }; return <form className="config-editor" onSubmit={submit}><h4>{title}</h4>{values.map((item, index) => <div className="config-row" key={item.slug}><code>{item.slug}</code><input name={`title-${index}`} aria-label={`${title} ${item.slug}`} defaultValue={item.title} /><input name={`color-${index}`} aria-label={`${t("admin.color")} ${item.slug}`} defaultValue={item.color} /><label><input type="checkbox" name={`active-${index}`} defaultChecked={item.active} />{t("admin.active")}</label></div>)}<button className="primary" disabled={readOnly}>{t("core.save")}</button></form>; }
