import { useCallback, useEffect, useState, type FormEvent } from "react";
import { ENTITY_ID_PREFIX, newUniqueEntityId } from "@gitpm/shared";
import type { GitPmApi } from "./api.js";
import { message, type Locale, type MessageKey } from "./i18n.js";
import type { DraftStatus, EntityResult, GitPmDocument, GitPmRole } from "./types.js";
import { AsyncBoundary, useAsyncLoad } from "./async-data.js";

type AdminSurface = "people" | "calendar" | "settings";
const text = (document: GitPmDocument, key: string) => typeof document[key] === "string" ? document[key] as string : "";
const number = (document: GitPmDocument, key: string) => typeof document[key] === "number" ? document[key] as number : 0;
const strings = (document: GitPmDocument, key: string) => Array.isArray(document[key]) ? (document[key] as unknown[]).filter((item): item is string => typeof item === "string") : [];
const numbers = (document: GitPmDocument, key: string) => Array.isArray(document[key]) ? (document[key] as unknown[]).filter((item): item is number => typeof item === "number") : [];
const split = (value: FormDataEntryValue | null) => String(value ?? "").split(",").map((item) => item.trim()).filter(Boolean);

export function AdminWorkspace({ api, draft, role, locale, surface, confirmAction = () => true, onChanged }: { readonly api: GitPmApi; readonly draft: DraftStatus; readonly role: GitPmRole; readonly locale: Locale; readonly surface: AdminSurface; readonly confirmAction?: (message: string) => boolean; readonly onChanged: () => Promise<void> }) {
  const t = (key: MessageKey, values?: Readonly<Record<string, string | number>>) => message(locale, key, values);
  const [calendars, setCalendars] = useState<readonly EntityResult[]>([]);
  const [people, setPeople] = useState<readonly EntityResult[]>([]);
  const [teams, setTeams] = useState<readonly EntityResult[]>([]);
  const [statuses, setStatuses] = useState<EntityResult | null>(null);
  const [issueTypes, setIssueTypes] = useState<EntityResult | null>(null);
  const [fingerprint, setFingerprint] = useState(draft.fingerprint);
  const [error, setError] = useState<string | null>(null);
  const [peopleQuery, setPeopleQuery] = useState("");
  const loadRequest = useAsyncLoad();
  const readOnly = role !== "Maintainer" || draft.writer_mode !== "ui" || draft.state !== "open" || draft.changed_externally === true;

  const load = useCallback(async () => {
    await loadRequest.run(async () => {
      const [nextCalendars, nextPeople, nextTeams, nextStatuses, nextIssueTypes] = await Promise.all([
        api.listEntities(draft.draft_id, "calendars"), api.listEntities(draft.draft_id, "people"), api.listEntities(draft.draft_id, "teams"), api.getConfiguration(draft.draft_id, "statuses"), api.getConfiguration(draft.draft_id, "issue-types"),
      ]);
      return { nextCalendars, nextPeople, nextTeams, nextStatuses, nextIssueTypes };
    }, ({ nextCalendars, nextPeople, nextTeams, nextStatuses, nextIssueTypes }) => {
      setCalendars(nextCalendars); setPeople(nextPeople); setTeams(nextTeams); setStatuses(nextStatuses); setIssueTypes(nextIssueTypes);
      setFingerprint(nextCalendars[0]?.draft_fingerprint ?? nextPeople[0]?.draft_fingerprint ?? nextTeams[0]?.draft_fingerprint ?? nextStatuses.draft_fingerprint);
    });
  }, [api, draft.draft_id, draft.external_fingerprint, loadRequest.run]);
  useEffect(() => { void load(); }, [load]);

  const mutate = async (operation: () => Promise<EntityResult>) => { setError(null); try { const result = await operation(); setFingerprint(result.draft_fingerprint); await load(); await onChanged(); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } };
  const remove = async (operation: () => Promise<void>) => { setError(null); try { await operation(); await load(); await onChanged(); } catch (caught) { setError(caught instanceof Error ? caught.message : String(caught)); } };
  const activeCalendars = calendars.filter((item) => item.document.lifecycle === "active");
  const activePeople = people.filter((item) => item.document.lifecycle === "active");
  const visiblePeople = activePeople.filter((item) => `${text(item.document, "name")} ${text(item.document, "email")}`.toLocaleLowerCase(locale).includes(peopleQuery.trim().toLocaleLowerCase(locale)));
  const activeTeams = teams.filter((item) => item.document.lifecycle === "active");
  const confirmDelete = (name: string) => confirmAction(t("core.deleteConfirm", { name }));
  const surfaceHeading: MessageKey = surface === "people" ? "nav.people" : surface === "calendar" ? "nav.calendar" : "nav.settings";

  const createCalendar = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const document = { schema: "gitpm/calendar@1", id: newUniqueEntityId(ENTITY_ID_PREFIX.calendar, new Set(calendars.map((item) => item.document.id))), name: String(data.get("name")), working_weekdays: data.getAll("weekdays").map(Number), holidays: split(data.get("holidays")), lifecycle: "active" } as GitPmDocument; void mutate(async () => await api.createEntity(draft.draft_id, "calendars", fingerprint, document)); event.currentTarget.reset(); };
  const createPerson = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const email = String(data.get("email") ?? ""); const document = { schema: "gitpm/person@1", id: newUniqueEntityId(ENTITY_ID_PREFIX.person, new Set(people.map((item) => item.document.id))), name: String(data.get("name")), weekly_capacity_hours: Number(data.get("capacity")), calendar: String(data.get("calendar")), lifecycle: "active", ...(email ? { email } : {}) } as GitPmDocument; void mutate(async () => await api.createEntity(draft.draft_id, "people", fingerprint, document)); event.currentTarget.reset(); };
  const createTeam = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const document = { schema: "gitpm/team@1", id: newUniqueEntityId(ENTITY_ID_PREFIX.team, new Set(teams.map((item) => item.document.id))), name: String(data.get("name")), members: data.getAll("members").map(String), lifecycle: "active" } as GitPmDocument; void mutate(async () => await api.createEntity(draft.draft_id, "teams", fingerprint, document)); event.currentTarget.reset(); };

  return <section className="admin-workspace"><div className="section-heading"><span className="eyebrow draft-context-id">{draft.draft_id}</span><h2>{t(surfaceHeading)}</h2></div>
    {role !== "Maintainer" && <div className="alert warning">{t("admin.maintainerOnly")}</div>}{error !== null && <div className="alert error">{error}</div>}
    <AsyncBoundary state={loadRequest.state} loading={t("status.loading")} retry={() => { void load(); }} error={(loadError, retry) => <div className="alert error">{loadError}<button onClick={retry}>{t("status.retry")}</button></div>}>
    <>
    {surface === "calendar" && <section className="card"><details className="create-disclosure"><summary>{t("admin.createCalendar")}</summary><form className="admin-create calendar-create" onSubmit={createCalendar}><label>{t("core.name")}<input name="name" required /></label><WeekdayChecks selected={[1, 2, 3, 4, 5]} t={t} /><label>{t("admin.holidays")}<input name="holidays" placeholder="2026-01-01" /></label><button className="primary" disabled={readOnly}>{t("admin.createCalendar")}</button></form></details><div className="admin-grid">{activeCalendars.map((entity) => <CalendarEditor key={entity.document.id} {...{ api, draft, entity, fingerprint, readOnly, t, mutate, remove, confirmDelete }} />)}</div></section>}
    {surface === "people" && <div className="admin-columns"><section className="card"><div className="card-heading"><h3>{t("admin.people")}</h3><label className="search-field">{t("admin.peopleSearch")}<input type="search" value={peopleQuery} onChange={(event) => setPeopleQuery(event.target.value)} /></label></div><details className="create-disclosure"><summary>{t("admin.createPerson")}</summary><form className="admin-create" onSubmit={createPerson}><label>{t("core.name")}<input name="name" required /></label><label>{t("admin.email")}<input name="email" type="email" /></label><label>{t("admin.capacity")}<input name="capacity" type="number" min="0" step="0.25" defaultValue="40" required /></label><label>{t("admin.calendar")}<select name="calendar" required>{activeCalendars.map((item) => <option value={item.document.id} key={item.document.id}>{text(item.document, "name")}</option>)}</select></label><button className="primary" disabled={readOnly || activeCalendars.length === 0}>{t("admin.createPerson")}</button></form></details><div className="admin-grid">{visiblePeople.map((entity) => <PersonEditor key={entity.document.id} {...{ api, draft, entity, fingerprint, readOnly, t, calendars: activeCalendars, mutate, remove, confirmDelete }} />)}</div></section>
      <section className="card"><h3>{t("admin.teams")}</h3><details className="create-disclosure"><summary>{t("admin.createTeam")}</summary><form className="admin-create" onSubmit={createTeam}><label>{t("core.name")}<input name="name" required /></label><MemberChecks people={activePeople} selected={[]} t={t} /><button className="primary" disabled={readOnly}>{t("admin.createTeam")}</button></form></details><div className="admin-grid">{activeTeams.map((entity) => <TeamEditor key={entity.document.id} {...{ api, draft, entity, fingerprint, readOnly, t, people: activePeople, mutate, remove, confirmDelete }} />)}</div></section></div>}
    {surface === "settings" && <section className="card"><h3>{t("admin.settings")}</h3><div className="alert info">{t("admin.noServerConfig")}</div><div className="admin-columns">{statuses !== null && <ConfigEditor api={api} draft={draft} entity={statuses} kind="statuses" listKey="statuses" title={t("admin.statuses")} readOnly={readOnly} t={t} mutate={mutate} />}{issueTypes !== null && <ConfigEditor api={api} draft={draft} entity={issueTypes} kind="issue-types" listKey="issue_types" title={t("admin.issueTypes")} readOnly={readOnly} t={t} mutate={mutate} />}</div></section>}
    </>
    </AsyncBoundary>
  </section>;
}

interface EditorProps { readonly api: GitPmApi; readonly draft: DraftStatus; readonly entity: EntityResult; readonly fingerprint: string; readonly readOnly: boolean; readonly t: (key: MessageKey, values?: Readonly<Record<string, string | number>>) => string; readonly mutate: (operation: () => Promise<EntityResult>) => Promise<void>; readonly remove: (operation: () => Promise<void>) => Promise<void>; readonly confirmDelete: (name: string) => boolean }
const ActionButtons = ({ disabled, save, archive, remove, t }: { disabled: boolean; save: (form: HTMLFormElement) => void; archive: () => void; remove: () => void; t: (key: MessageKey) => string }) => <div className="admin-actions"><button type="button" className="primary" disabled={disabled} onClick={(event) => { if (event.currentTarget.form !== null) save(event.currentTarget.form); }}>{t("core.save")}</button><details className="more-actions"><summary>{t("core.moreActions")}</summary><div><button type="button" disabled={disabled} onClick={archive}>{t("core.archive")}</button><button type="button" className="danger" disabled={disabled} onClick={remove}>{t("core.delete")}</button></div></details></div>;

function CalendarEditor(props: EditorProps) { const { api, draft, entity, fingerprint, readOnly, t, mutate, remove, confirmDelete } = props; const name = text(entity.document, "name"); const weekdays = numbers(entity.document, "working_weekdays"); const submit = (form: HTMLFormElement) => { const data = new FormData(form); void mutate(async () => await api.updateEntity(draft.draft_id, "calendars", entity, fingerprint, { ...entity.document, name: String(data.get("name")), working_weekdays: data.getAll("weekdays").map(Number), holidays: split(data.get("holidays")) })); }; return <article className="admin-card admin-card-summary"><strong>{name}</strong><span>{weekdays.map((day) => t(`admin.day${day}` as MessageKey)).join(", ")}</span><span>{strings(entity.document, "holidays").length} {t("admin.holidays").split(" ")[0]?.toLocaleLowerCase()}</span><details className="edit-disclosure"><summary>{t("admin.editCalendar")}</summary><form onSubmit={(event) => event.preventDefault()}><label>{t("core.name")}<input name="name" aria-label={`${t("core.name")} ${name}`} defaultValue={name} /></label><WeekdayChecks selected={weekdays} t={t} /><label>{t("admin.holidays")}<input name="holidays" aria-label={`${t("admin.holidays")} ${name}`} defaultValue={strings(entity.document, "holidays").join(",")} /></label><ActionButtons disabled={readOnly} t={t} save={submit} archive={() => { void mutate(async () => await api.archiveEntity(draft.draft_id, "calendars", entity, fingerprint)); }} remove={() => { if (confirmDelete(name)) void remove(async () => await api.deleteEntity(draft.draft_id, "calendars", entity, fingerprint)); }} /></form></details></article>; }

function PersonEditor(props: EditorProps & { calendars: readonly EntityResult[] }) { const { api, draft, entity, fingerprint, readOnly, t, calendars, mutate, remove, confirmDelete } = props; const name = text(entity.document, "name"); const calendar = calendars.find((item) => item.document.id === text(entity.document, "calendar")); const calendarName = calendar === undefined ? "" : text(calendar.document, "name"); const update = (form: HTMLFormElement) => { const data = new FormData(form); const email = String(data.get("email")); void mutate(async () => await api.updateEntity(draft.draft_id, "people", entity, fingerprint, { ...entity.document, name: String(data.get("name")), email: email || undefined, weekly_capacity_hours: Number(data.get("capacity")), calendar: String(data.get("calendar")) })); }; return <article className="admin-card admin-card-summary"><strong>{name}</strong>{text(entity.document, "email") !== "" && <span>{text(entity.document, "email")}</span>}<span>{t("admin.capacitySummary", { count: number(entity.document, "weekly_capacity_hours"), calendar: calendarName })}</span><details className="edit-disclosure"><summary>{t("admin.editPerson")}</summary><form onSubmit={(event) => event.preventDefault()}><label>{t("core.name")}<input name="name" aria-label={`${t("core.name")} ${name}`} defaultValue={name} /></label><label>{t("admin.email")}<input name="email" aria-label={`${t("admin.email")} ${name}`} defaultValue={text(entity.document, "email")} /></label><label>{t("admin.capacity")}<input name="capacity" type="number" min="0" step="0.25" aria-label={`${t("admin.capacity")} ${name}`} defaultValue={number(entity.document, "weekly_capacity_hours")} /></label><label>{t("admin.calendar")}<select name="calendar" aria-label={`${t("admin.calendar")} ${name}`} defaultValue={text(entity.document, "calendar")}>{calendars.map((item) => <option key={item.document.id} value={item.document.id}>{text(item.document, "name")}</option>)}</select></label><ActionButtons disabled={readOnly} t={t} save={update} archive={() => { void mutate(async () => await api.archiveEntity(draft.draft_id, "people", entity, fingerprint)); }} remove={() => { if (confirmDelete(name)) void remove(async () => await api.deleteEntity(draft.draft_id, "people", entity, fingerprint)); }} /></form></details></article>; }

function MemberChecks({ people, selected, t }: { people: readonly EntityResult[]; selected: readonly string[]; t: (key: MessageKey) => string }) { return <fieldset><legend>{t("admin.members")}</legend>{people.map((person) => <label key={person.document.id}><input type="checkbox" name="members" value={person.document.id} defaultChecked={selected.includes(person.document.id)} />{text(person.document, "name")}</label>)}</fieldset>; }
function WeekdayChecks({ selected, t }: { selected: readonly number[]; t: (key: MessageKey) => string }) { return <fieldset className="weekday-checks"><legend>{t("admin.weekdays")}</legend>{[1, 2, 3, 4, 5, 6, 7].map((day) => <label key={day}><input type="checkbox" name="weekdays" value={day} defaultChecked={selected.includes(day)} />{t(`admin.day${day}` as MessageKey)}</label>)}</fieldset>; }
function TeamEditor(props: EditorProps & { people: readonly EntityResult[] }) { const { api, draft, entity, fingerprint, readOnly, t, people, mutate, remove, confirmDelete } = props; const name = text(entity.document, "name"); const selected = strings(entity.document, "members"); const update = (form: HTMLFormElement) => { const data = new FormData(form); void mutate(async () => await api.updateEntity(draft.draft_id, "teams", entity, fingerprint, { ...entity.document, name: String(data.get("name")), members: data.getAll("members").map(String) })); }; return <article className="admin-card admin-card-summary"><strong>{name}</strong><span>{t("admin.memberCount", { count: selected.length })}</span><details className="edit-disclosure"><summary>{t("admin.editTeam")}</summary><form onSubmit={(event) => event.preventDefault()}><label>{t("core.name")}<input name="name" aria-label={`${t("core.name")} ${name}`} defaultValue={name} /></label><MemberChecks people={people} selected={selected} t={t} /><ActionButtons disabled={readOnly} t={t} save={update} archive={() => { void mutate(async () => await api.archiveEntity(draft.draft_id, "teams", entity, fingerprint)); }} remove={() => { if (confirmDelete(name)) void remove(async () => await api.deleteEntity(draft.draft_id, "teams", entity, fingerprint)); }} /></form></details></article>; }

interface ConfigValue { readonly slug: string; readonly title: string; readonly color: string; readonly active: boolean }
function ConfigEditor({ api, draft, entity, kind, listKey, title, readOnly, t, mutate }: { readonly api: GitPmApi; readonly draft: DraftStatus; readonly entity: EntityResult; readonly kind: "statuses" | "issue-types"; readonly listKey: "statuses" | "issue_types"; readonly title: string; readonly readOnly: boolean; readonly t: (key: MessageKey) => string; readonly mutate: (operation: () => Promise<EntityResult>) => Promise<void> }) { const values = Array.isArray(entity.document[listKey]) ? entity.document[listKey] as ConfigValue[] : []; const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const next = values.map((item, index) => ({ slug: item.slug, title: String(data.get(`title-${index}`)), color: String(data.get(`color-${index}`)), active: data.get(`active-${index}`) === "on" })); void mutate(async () => await api.updateConfiguration(draft.draft_id, kind, entity, entity.draft_fingerprint, { ...entity.document, [listKey]: next })); }; return <form className="config-editor" onSubmit={submit}><h4>{title}</h4>{values.map((item, index) => <div className="config-row" key={item.slug}><code>{item.slug}</code><input name={`title-${index}`} aria-label={`${title} ${item.slug}`} defaultValue={item.title} /><label className="color-field"><span aria-hidden="true" style={{ backgroundColor: item.color }} /><input name={`color-${index}`} aria-label={`${t("admin.color")} ${item.slug}`} defaultValue={item.color} /></label><label><input type="checkbox" name={`active-${index}`} defaultChecked={item.active} />{t("admin.active")}</label></div>)}<button className="primary" disabled={readOnly}>{t("core.save")}</button></form>; }
